// <auto-generated />
namespace MovieDb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class userFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061805363_userFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
